### PR TITLE
Added support for formats inferring

### PR DESCRIPTION
**Pull request by roll**
- connects #98

### CODE REVIEW

**Comment by Stephen-Gates** [comment]
Thanks @roll will take a look

**Comment by Stephen-Gates** [comment]
@roll looks good. 
I'm wondering if `year` and `yearmonth` types are included in the "common patterns" you mention above or if you're referring to `date`, `time` or `datetime` with a `pattern` format?

**Comment by roll** [comment]
@Stephen-Gates 
I've added `yearmonth`. 

Added next steps to https://github.com/frictionlessdata/tableschema-js/issues/98

**Comment by Stephen-Gates** [comment]
Awesome thanks @roll

**Comment by Stephen-Gates** [comment]
@roll just trying it out in Data Curator...

`email` and `uri` formats worked fine

screenshot 2017-10-28 06 13 12

Interesting result with date, I would have expected a `date` type rather than `yearmonth`.
screenshot 2017-10-28 06 19 05

Would you like me to raise an issue?

**Comment by roll** [comment]
Yea.. It should be a bug.

**Pull request merged**
