### PR TITLE
Add caseSensitive to Table constructor to schema field names validation

### LINKED ISSUE #185: Field name/header comparison should not be case sensitive
# Overview

According to https://specs.frictionlessdata.io/table-schema/#field-descriptors, "name SHOULD NOT be considered case sensitive in determining uniqueness.". However, the library does not compare and ignore case. See https://github.com/frictionlessdata/tableschema-js/blob/37f02247e0ce35f382ad815121bd64877e9718af/src/table.js#L152

Can this be fixed or provide options to ignore case, please? Friendlier error message identifying which columns are the problem would also be more useful to the users than "The column header names do not match the field names in the schema" as well.

---

Please preserve this line to notify @roll (lead of this repository)

### PR DESCRIPTION
**Pull request by aivuk**
- fixes #185 

---

Base on the bug reported by @paulboony  at https://github.com/frictionlessdata/tableschema-js/issues/185 I implemented the option to load a table passing an argument caseSensitive, that will make the check between the table data header names and the field names on the schema case sensitive. For now I left the default as case sensitive, because this is the current tableschema-js behavior. 

You can now load a schema for a table not case sensitively as:

`const table = await Table.load('data.csv', { schema: 'schema.json', caseSensitive: false })`

### CODE REVIEW

**Comment by paulboony** [comment]
Thank, @aivuk. Can you also add this new `caseSensitive` option to `index.d.ts` for typescript support, please? https://github.com/frictionlessdata/tableschema-js/blob/37f02247e0ce35f382ad815121bd64877e9718af/index.d.ts#L16

**Review by paulboony — APPROVED** [review]

**Comment by paulboony** [comment]
@aivuk Who can review this PR to move this along?

**Comment by aivuk** [comment]
> @aivuk Who can review this PR to move this along?

@roll is the one, but this week can be a bit complicate for him to do it.

**Review by roll — APPROVED** [review]
Thanks!

**Review by roll — CHANGES_REQUESTED** [review]
It seems there is a conflict. @aivuk can you please resolve it?

**Review by roll — APPROVED** [review]

**Pull request merged**
