### PR TITLE
Feature - Adding CSV parse options param

### PR DESCRIPTION
**Pull request by felipesabino**
- connects #82

---

Adding CSV parse options as an optional parameter to load data

It is an expansion on #80 and #81 where any [csv-parser option](http://csv.adaltas.com/parse/#parser-options) can be provided on `Table.load`, allowing `tableschema-js` usage for any CSV formats already supported by [`csv-parse`](http://csv.adaltas.com/parse) including non-standard ones, like the example added for testing which is using `;` as delimiter

### CODE REVIEW

**Comment by roll** [comment]
@felipesabino 
Thanks. It's great!

In Python we use slightly different API for it:
```python
Table(data, schema, delimiter=';', ...)
```

So I think we should follow in for consistency and use:
```javascript
Table.load(data, {schema, delimiter: ';', ...})
```

Internally using object rest properties:
```javascript
static async load(source, {schema, strict=false, headers=1, ...parseOptions})
```

I think this API is less overwhelming than parse options object inside other options object. 

WDYT?

**Comment by felipesabino** [comment]
(Wrong clicked to close the PR. Usability on mobile is not the best, sorry)

> In Python we use slightly different API for it:
>Table(data, schema, delimiter=';', ...)

I am not familiar with the Python API, but how do you handle other options? Does this `...` mean you expose all `csv-parse` options explicitly one by one?

If not, then I am not sure... There is already a hard coded csv param internally and exposing the params would also enable overring that.

People have weird data formats, specially regarding CSV files being mostly created by non-techincal people that have no idea that a CSV standard even exists (in most of my past cases anyway) and enabling the project handle these weird formats may require exposing more parsing options. That was my reasoning for adding the whole object instead of a few selected options.

But I am also all down for consistency, just not so sure what the best approach would be in this case

**Comment by roll** [comment]
@felipesabino 
I mean technically we could just catch `parseOptions` as a rest object properties of `Table` options. I doesn't change any functionality just replace this API:
```javascript
Table.load(data, {schema, parseOptions: {parseOption1: parseOption1, parseOption2: parseOption2, ...}})
```
by 
```javascript
Table.load(data, {schema, parseOption1: parseOption1, parseOption2: parseOption2, ...})
```

**Comment by felipesabino** [comment]
Oh, ok, I think got it. 

I just updated `Table.load` to use rest parameters instead.

One caveat is that I also needed to update babel options to use TC-39 `stage-3` features, there are more info at https://github.com/babel/babel-loader/issues/170#issuecomment-290298512

Let me know if that is ok or if I should go through other paths.

**Comment by roll** [comment]
@felipesabino 
Thanks! It's a great contribution.

**Comment by roll** [comment]
Released as `tableschema@1.1` - https://www.npmjs.com/package/tableschema

**Pull request merged**
